### ISSUE TITLE
进不去系统

### ISSUE THREAD

**Issue by LJAYi** [charlesSheep/-gs65-opencore-eif#1]
我的gs65由于屏幕品质出现了问题，售后换了一块LG的，具体是LG LP156WFG-SPB3 (LGD0625)，之后再没进过黑果了，再开机第二阶段直接重启，就是屏幕暗一下之后，楼主方便帮忙排查一下问题么

**Comment by charlesSheep** [comment]
> 我的gs65由于屏幕品质出现了问题，售后换了一块LG的，具体是LG LP156WFG-SPB3 (LGD0625)，之后再没进过黑果了，再开机第二阶段直接重启，就是屏幕暗一下之后，楼主方便帮忙排查一下问题么

你也是8代的机器吗？换了屏后，可能要修改edid,你可以进win提取修改的。

**Comment by LJAYi** [comment]
> > 我的gs65由于屏幕品质出现了问题，售后换了一块LG的，具体是LG LP156WFG-SPB3 (LGD0625)，之后再没进过黑果了，再开机第二阶段直接重启，就是屏幕暗一下之后，楼主方便帮忙排查一下问题么
> 
> 你也是8代的机器吗？换了屏后，可能要修改edid,你可以进win提取修改的。

是的，我也是八代1070应该和您是一样配置，EDID我直接删除了，也是没法。跑v（可能是水平不够）没有看出是什么导致的重启，我使用的是苹果拆机卡，远景上我也回复了您，方便交流一下么？qq：1048461824
