### ISSUE TITLE
Kernel里面的Kext有重复

### ISSUE THREAD

**Issue by JessyTang** [charlesSheep/-gs65-opencore-eif#12]
VoodooPS2的几个kext有两个版本2.1.5和2.2.7，会冲突导致CPU Panic。

**Comment by JessyTang** [comment]
还有AirportItlwm官方Wiki说要开启Apple Secure Boot，但是实测只有把apple secure model设置成disable才能正常使用Intel WIFI

**Comment by charlesSheep** [comment]
> 
在kexts文件夹下，有一个VoodooPS2Controller.kext.bak.kext,把这个删除掉，这是旧的，之前更新忘删除了
